services:
  web:
    container_name: simple-aircraft-manager
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_ENGINE: postgresql
      DATABASE_NAME: simpleaircraft
      DATABASE_USER: simpleaircraft
      DATABASE_PASSWORD: strongpassword
      DATABASE_HOST: db
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@domain.com
      DJANGO_SUPERUSER_PASSWORD: password
      DJANGO_SECRET_KEY: yoursecretkey
      DJANGO_DEBUG: true
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      OIDC_ENABLED: false
      OIDC_OP_DISCOVERY_ENDPOINT: endpoint
      OIDC_RP_CLIENT_ID: id
      OIDC_RP_CLIENT_SECRET: secret
      TZ: America/New_York
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: simpleaircraft
      POSTGRES_USER: simpleaircraft
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
