services:
  web:
    container_name: simple-aircraft-manager
    image: barrettefab/simple-aircraft-manager:latest
    expose:
      - 8000
    environment:
      DATABASE_ENGINE: postgresql
      DATABASE_NAME: simpleaircraft
      DATABASE_USER: simpleaircraft
      DATABASE_PASSWORD: simpleaircraft
      DATABASE_HOST: db
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}:true
      DJANGO_ALLOWED_HOSTS: ${DOMAIN}
      OIDC_ENABLED: ${OIDC_ENABLED}
      OIDC_OP_DISCOVERY_ENDPOINT: ${OIDC_OP_DISCOVERY_ENDPOINT}
      OIDC_RP_CLIENT_ID: ${OIDC_RP_CLIENT_ID}
      OIDC_RP_CLIENT_SECRET: ${OIDC_RP_CLIENT_SECRET}
      TZ: ${TZ}:UTC
      DJANGO_CSRF_TRUSTED_ORIGINS: https://${DOMAIN}
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_default
      # HTTP
      traefik.http.routers.simple-aircraft-manager.entrypoints: web,websecure
      traefik.http.routers.simple-aircraft-manager.rule: Host(`${DOMAIN}`)
      traefik.http.routers.simple-aircraft-manager.service: simple-aircraft-manager-service
      traefik.http.services.simple-aircraft-manager-service.loadbalancer.server.port: 8000
      traefik.http.routers.simple-aircraft-manager.tls: true
      traefik.http.routers.simple-aircraft-manager.tls.certresolver: production
      # Middlewares
      traefik.http.routers.simple-aircraft-manager.middlewares: middlewares-authentik@file
    networks:
      - simple-aircraft-manager
      - default

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: simpleaircraft
      POSTGRES_USER: simpleaircraft
      POSTGRES_PASSWORD: simpleaircraft
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  simple-aircraft-manager:
  default:
    external: true
    name: traefik_default